# --------------------
# github actions
# --------------------

name: github-actions-for-ci-cd
env: 
  APPLICATION_NAME    : "RELAB"
  DEPLOY_PACKAGE_NAME : "first-deploy-version-${{ github.sha }}"

on:
  push:
    branches:
      - main
  
jobs:
    
  testing:
    runs-on: ubuntu-latest
    # needs: [deploy]
    steps:
    - name : testing first job
      run  : echo "$(curl "ipinfo.io/ip")"

    - name : testing second job
      run  : |
        echo "testing 1"
        echo "testing 2"
        echo "application name is ${{ env.APPLICATION_NAME }}"

    - name : list of current directory 1
      run  : ls -la

    - name : the git clone repository
      uses : actions/checkout@v1

    - name : list of current directory 2
      run  : ls -la
  deploy:
    runs-on : ubuntu-latest
    needs   : 
    - testing
    
    steps:
    - name : deploy first job
      run  : echo "$(w)"]

    - name : deploy second job
      run  : |
        echo "deploy 1"
        echo "see ${{ env.DEPLOY_PACKAGE_NAME }}"
    - name : lets test some packages if theye are here 1
      run  : aws --version

    - name : lets test some packages if theye are here 2
      run  : zip 
