# --------------------
# github actions
# --------------------

name: github-actions-for-ci-cd

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: first job
      run: echo "$(curl "ipinfo.io/ip")"
    
  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: second job
      run: echo "$(w)"]
