# --------------------
# github actions
# --------------------

name: github-actions-for-ci-cd
env : 
  APPLICATION_NAME    : "RELAB"
  DEPLOY_PACKAGE_NAME : "first-deploy-version-$ {{ github.sha }}"

on:
  push:
    branches:
      - main
  
jobs:
  testing:
    runs-on: ubuntu-latest
    # needs: [deploy]
    
    steps:
    - name: testing first job
      run : echo "$(curl "ipinfo.io/ip")"

    - name: testing second job
      run: |
        echo "testing 1"
        echo "testing 2"
        echo "${{ env.APLLICATION_NAME }}"
    
  
  deploy:
    runs-on: ubuntu-latest
    needs  : 
    - testing
    
    steps:
    - name: deploy first job
      run : echo "$(w)"]

    - name: deploy second job
      run : |
        echo "deploy 1"
        echo "${{ env.DEPLOY_PACKAGE_NAME }}"


