# --------------------
# github actions
# --------------------

name: github-action-for-ci

on:
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello message
      run: echo "aaaa"
    
  
  my_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello message
      run: echo "bbbb"
